### ISSUE TITLE
[PROBLEM] 169. Majority Element

### ISSUE THREAD

**Issue by godkingjay** [godkingjay/LeetCode#107]
### Difficulty

Easy

### Problem Description

<div class="xFUwe" data-track-load="description_content"><p>Given an array <code>nums</code> of size <code>n</code>, return <em>the majority element</em>.</p>

<p>The majority element is the element that appears more than <code>⌊n / 2⌋</code> times. You may assume that the majority element always exists in the array.</p>

<p><strong class="example">Example 1:</strong></p>
<pre><strong>Input:</strong> nums = [3,2,3]
<strong>Output:</strong> 3
</pre><p><strong class="example">Example 2:</strong></p>
<pre><strong>Input:</strong> nums = [2,2,1,1,1,2,2]
<strong>Output:</strong> 2
</pre>

<p><strong>Constraints:</strong></p>

<ul>
	<li><code>n == nums.length</code></li>
	<li><code>1 &lt;= n &lt;= 5 * 10<sup>4</sup></code></li>
	<li><code>-10<sup>9</sup> &lt;= nums[i] &lt;= 10<sup>9</sup></code></li>
</ul>

<strong>Follow-up:</strong> Could you solve the problem in linear time and in <code>O(1)</code> space?</div>

### Link

https://leetcode.com/problems/majority-element/

**Comment by vagxrth** [comment]
hey @godkingjay I would love to work on this issue

**Comment by Karanjamwal21** [comment]
Hi it's my first time to open source. I want to do this work. 
pls sign me the work.
