### ISSUE TITLE
[PROBLEM] 342. Power of Four

### ISSUE THREAD

**Issue by godkingjay** [godkingjay/LeetCode#168]
### Difficulty

Easy

### Problem Description

<div class="xFUwe" data-track-load="description_content">
<p>Given an integer <code>n</code>, return <em><code>true</code> if it is a power of four. Otherwise, return <code>false</code></em>.</p>

<p>An integer <code>n</code> is a power of four, if there exists an integer <code>x</code> such that <code>n == 4<sup>x</sup></code>.</p>

<p><strong class="example">Example 1:</strong></p>
<pre><strong>Input:</strong> n = 16
<strong>Output:</strong> true
</pre><p><strong class="example">Example 2:</strong></p>
<pre><strong>Input:</strong> n = 5
<strong>Output:</strong> false
</pre><p><strong class="example">Example 3:</strong></p>
<pre><strong>Input:</strong> n = 1
<strong>Output:</strong> true
</pre>

<p><strong>Constraints:</strong></p>

<ul>
	<li><code>-2<sup>31</sup> &lt;= n &lt;= 2<sup>31</sup> - 1</code></li>
</ul>

<strong>Follow up:</strong> Could you solve it without loops/recursion?</div>

### Link

https://leetcode.com/problems/power-of-four/

**Comment by supunvindula** [comment]
Hi there! I'm interested in working on this issue. Could you please assign it to me? I believe I can make a valuable contribution to this task.

Looking forward to your response. Thanks!

**Comment by pv-vardhan** [comment]
I hope you will like my Pull Request of this problem
