### ISSUE TITLE
[PROBLEM] 5. Longest Palindromic Substring

### ISSUE THREAD

**Issue by godkingjay** [godkingjay/LeetCode#182]
### Difficulty

Medium

### Problem Description

<div class="xFUwe" data-track-load="description_content">

<p>Given a string <code>s</code>, return <i>the longest palindromic substring</i> in <code>s</code>.</p>

<p><strong class="example">Example 1:</strong></p>

<pre><strong>Input:</strong> s = "babad"
<strong>Output:</strong> "bab"
<strong>Explanation:</strong> "aba" is also a valid answer.
</pre>

<p><strong class="example">Example 2:</strong></p>

<pre><strong>Input:</strong> s = "cbbd"
<strong>Output:</strong> "bb"
</pre>

<p><strong>Constraints:</strong></p>

<ul>
	<li><code>1 &lt;= s.length &lt;= 1000</code></li>
	<li><code>s</code> consist of only digits and English letters.</li>
</ul>
</div>

### Link

https://leetcode.com/problems/longest-palindromic-substring/

**Comment by chiku011** [comment]
can you assign this issue to me

**Comment by ankitkumar0622** [comment]
Hi @godkingjay can you please assign this task to me.
