### ISSUE TITLE
108. Convert Sorted Array to Binary Search Tree

### ISSUE THREAD

**Issue by Tusharknwl** [godkingjay/LeetCode#19]
please assign me this under hacktoberfest

**Comment by Tusharknwl** [comment]
- [x]  Added cpp Solution
- [x] Added java Solution
- [ ] Added py Solution
- [ ] Added js Solution

if anyone want to contribute solution in other languages (py, js etc.) for this, fill free to open a PR

**Comment by ruchikayadav1408** [comment]
I would like to contribute to this project.Please assign me this project.I will complete this project in just one day by using comments,appropriate variable names and in most efficient way.Greatly looking ahead to work with you.
