### ISSUE TITLE
[PROBLEM] 1220. Count Vowels Permutation

### ISSUE THREAD

**Issue by godkingjay** [godkingjay/LeetCode#190]
### Difficulty

Hard

### Problem Description

<div class="xFUwe" data-track-load="description_content">
<p>Given an integer <code>n</code>, your task is to count how many strings of length <code>n</code> can be formed under the following rules:</p>

<ul>
	<li>Each character is a lower case vowel&nbsp;(<code>'a'</code>, <code>'e'</code>, <code>'i'</code>, <code>'o'</code>, <code>'u'</code>)</li>
	<li>Each vowel&nbsp;<code>'a'</code> may only be followed by an <code>'e'</code>.</li>
	<li>Each vowel&nbsp;<code>'e'</code> may only be followed by an <code>'a'</code>&nbsp;or an <code>'i'</code>.</li>
	<li>Each vowel&nbsp;<code>'i'</code> <strong>may not</strong> be followed by another <code>'i'</code>.</li>
	<li>Each vowel&nbsp;<code>'o'</code> may only be followed by an <code>'i'</code> or a&nbsp;<code>'u'</code>.</li>
	<li>Each vowel&nbsp;<code>'u'</code> may only be followed by an <code>'a'.</code></li>
</ul>

<p>Since the answer&nbsp;may be too large,&nbsp;return it modulo <code>10^9 + 7.</code></p>

<p><strong class="example">Example 1:</strong></p>

<pre><strong>Input:</strong> n = 1
<strong>Output:</strong> 5
<strong>Explanation:</strong> All possible strings are: "a", "e", "i" , "o" and "u".
</pre>

<p><strong class="example">Example 2:</strong></p>

<pre><strong>Input:</strong> n = 2
<strong>Output:</strong> 10
<strong>Explanation:</strong> All possible strings are: "ae", "ea", "ei", "ia", "ie", "io", "iu", "oi", "ou" and "ua".
</pre>

<p><strong class="example">Example 3:&nbsp;</strong></p>

<pre><strong>Input:</strong> n = 5
<strong>Output:</strong> 68</pre>

<p><strong>Constraints:</strong></p>

<ul>
	<li><code>1 &lt;= n &lt;= 2 * 10^4</code></li>
</ul>
</div>

### Link

https://leetcode.com/problems/count-vowels-permutation/

**Comment by ankitkumar0622** [comment]
Hi @godkingjay , can you please assign me this task

**Comment by VibhorGits** [comment]
Hey @godkingjay Can I work on this issue?

**Comment by ankitkumar0622** [comment]
Hi @godkingjay  i am unable to push the code . It is showing me this "remote: Permission to godkingjay/LeetCode.git denied to ankitkumar0622."

**Comment by godkingjay** [comment]
> Hi @godkingjay i am unable to push the code . It is showing me this "remote: Permission to godkingjay/LeetCode.git denied to ankitkumar0622."

You should first fork this repository then clone the forked repository locally, add your changes, then push your forked repository, and create a pull request to merge to this repository.

**Comment by VibhorGits** [comment]
Hey @godkingjay I think @ankitkumar0622 is right.
Although I was able to push the code to my local branch but not able to create a pull request.

**Comment by godkingjay** [comment]
> Hey @godkingjay I think @ankitkumar0622 is right. Although I was able to push the code to my local branch but not able to create a pull request.

You do have a pull request #195
