### ISSUE TITLE
[PROBLEM] 42. Trapping Rain Water

### ISSUE THREAD

**Issue by godkingjay** [godkingjay/LeetCode#203]
### Difficulty

Hard

### Problem Description

<div class="xFUwe" data-track-load="description_content">
<p>Given <code>n</code> non-negative integers representing an elevation map where the width of each bar is <code>1</code>, compute how much water it can trap after raining.</p>

<p><strong class="example">Example 1:</strong></p>
<img src="https://assets.leetcode.com/uploads/2018/10/22/rainwatertrap.png" style="width: 412px; height: 161px;">
<pre><strong>Input:</strong> height = [0,1,0,2,1,0,1,3,2,1,2,1]
<strong>Output:</strong> 6
<strong>Explanation:</strong> The above elevation map (black section) is represented by array [0,1,0,2,1,0,1,3,2,1,2,1]. In this case, 6 units of rain water (blue section) are being trapped.
</pre>

<p><strong class="example">Example 2:</strong></p>

<pre><strong>Input:</strong> height = [4,2,0,3,2,5]
<strong>Output:</strong> 9
</pre>

<p><strong>Constraints:</strong></p>

<ul>
	<li><code>n == height.length</code></li>
	<li><code>1 &lt;= n &lt;= 2 * 10<sup>4</sup></code></li>
	<li><code>0 &lt;= height[i] &lt;= 10<sup>5</sup></code></li>
</ul>
</div>

### Link

https://leetcode.com/problems/trapping-rain-water/

**Comment by ad-astra-per-ardua** [comment]
Can you assign to me? @godkingjay

**Comment by SureshPradhana** [comment]
i have done js solution for it @godkingjay 
my pull request https://github.com/godkingjay/LeetCode/pull/206

@d982h8st7, in which programming language are you working?

**Comment by ad-astra-per-ardua** [comment]
> i have done js solution for it @godkingjay my pull request #206
> 
> @d982h8st7, in which programming language are you working?

I'll work with python i think
