### ISSUE TITLE
13. Roman to Integer

### ISSUE THREAD

**Issue by PPraneesh** [godkingjay/LeetCode#29]
This is a leet code **Easy** level problem.
**Problem description:**
In this problem we will be given with a Roman Number we need to convert it and return the integer number of it.
I have done this problem in **Java.**
Please assign this to me, the solution is valid and it has a **run time of 2ms** and it beats **100% of users**.
Here is the screenshot of it
![image](https://github.com/godkingjay/LeetCode/assets/125351602/e9dcfb6b-0f18-47cd-908f-aeda3c612750)

**Comment by kittoteja** [comment]
please assigne me
