### ISSUE TITLE
problem: 557. Reverse Words in a String III

### ISSUE THREAD

**Issue by godkingjay** [godkingjay/LeetCode#3]
# [557. Reverse Words in a String III](https://leetcode.com/problems/reverse-words-in-a-string-iii/)

Given a string `s`, reverse the order of characters in each word within a sentence while still preserving whitespace and initial word order.

## Example 1:

```
Input: s = "Let's take LeetCode contest"
Output: "s'teL ekat edoCteeL tsetnoc"
```

## Example 2:

```
Input: s = "God Ding"
Output: "doG gniD"
```

## Constraints:
- `1 <= s.length <= 5 * 10^4`
- `s` contains printable ASCII characters.
- `s` does not contain any leading or trailing spaces.
- There is at least one word in `s`.
- All the words in `s` are separated by a single space.

**Comment by kevinpaul468** [comment]
made a python solution
will soon add java and c++

**Comment by kevinpaul468** [comment]
not getting the c++ solution

**Comment by godkingjay** [comment]
> not getting the c++ solution

Are you still working on this problem?

**Comment by kevinpaul468** [comment]
Nope

**Comment by godkingjay** [comment]
I'll be closing this issue, thank you!

- #23 
- #9
