### ISSUE TITLE
14. Longest Common Prefix

### ISSUE THREAD

**Issue by PPraneesh** [godkingjay/LeetCode#30]
It is a leet code **easy** level question.
**Question description:**
In this question we need to write a function to find the longest common prefix string amongst an array of strings. 
I solved this question using **Java.**
Can you please assign this issue to me I want to add this answer.

**Comment by kittoteja** [comment]
please assign me

**Comment by ruchikayadav1408** [comment]
I would like to contribute to this project.Please assign me this project.I will complete this project in just one day by using comments,appropriate variable names and in most efficient way.Greatly looking ahead to work with you.
