### ISSUE TITLE
problem: 229. Majority Element II

### ISSUE THREAD

**Issue by godkingjay** [godkingjay/LeetCode#43]
# Problem #229 ([Majority Element II](https://leetcode.com/problems/majority-element-ii/) | Array, Counting, Hash Table, Sorting)

<img src="https://img.shields.io/badge/-Medium-ffc022?style=for-the-badge&logo=LeetCode&logoColor=black" alt="Medium"/>

Given an integer array of size `n`, find all elements that appear more than `⌊ n/3 ⌋` times.

## Example 1

**Input:** `nums = [3,2,3]
**Output:** `[3]`

## Example 2:

**Input:** `nums = [1]`
**Output:** `[1]`

## Example 3:

**Input:** `nums = [1,2]`
**Output:** `[1,2]`

## Constraints:

- $1 <= nums.length <= 5 * 104$
- $-109 <= nums[i] <= 10^9$

**Comment by Joshna907** [comment]
Please assign me this issue @godkingjay
