### ISSUE TITLE
problem: 343. Integer Break

### ISSUE THREAD

**Issue by godkingjay** [godkingjay/LeetCode#44]
# Problem #343([Integer Break](https://leetcode.com/problems/integer-break/) | Dynamic Programmin, Math)

<img src="https://img.shields.io/badge/-Medium-ffc022?style=for-the-badge&logo=LeetCode&logoColor=black" alt="Medium"/>

Given an integer `n`, break it into the sum of `k` **positive integers**, where `k >= 2`, and maximize the product of those integers.

Return the *maximum product you can get.*

## Example 1:

**Input:** `n = 2`
**Output:** `1`
**Explanation:** `2 = 1 + 1, 1 × 1 = 1.`

## Example 2:

**Input:** `n = 10`
**Output:** `36`
**Explanation:** `10 = 3 + 3 + 4, 3 × 3 × 4 = 36.`

## Constraints:

- $2 <= n <= 58$

**Comment by vagxrth** [comment]
Hey, @godkingjay can you assign the issue to me?
