### ISSUE TITLE
[PROBLEM] 34. Find First and Last Position of Element in Sorted Array

### ISSUE THREAD

**Issue by godkingjay** [godkingjay/LeetCode#69]
### Difficulty

Hard

### Problem Description

Given an array of integers `nums` sorted in non-decreasing order, find the starting and ending position of a given `target` value.

If `target` is not found in the array, return `[-1, -1]`.

You must write an algorithm with `O(log n)` runtime complexity.

---

### Example 1:

**Input:** `nums = [5,7,7,8,8,10]`, `target = 8`
**Output:** `[3,4]`

### Example 2:

**Input:** `nums = [5,7,7,8,8,10]`, `target = 6`
**Output:** `[-1,-1]`

### Example 3:

**Input:** `nums = []`, `target = 0`
**Output:** `[-1,-1]`

---

### Constraints:
- $0 <= nums.length <= 105$
- $-109 <= nums[i] <= 109$
- $nums$ is a non-decreasing array.
- $109 <= target <= 109$

### Link

https://leetcode.com/problems/find-first-and-last-position-of-element-in-sorted-array/

**Comment by Pakeetharan** [comment]
@godkingjay Please assign this.

**Comment by VishnuAmit** [comment]
@godkingjay I would like to do this. Please assign it to me

**Comment by kittoteja** [comment]
Please assign it to me
