### ISSUE TITLE
[PROBLEM] 2251. Number of Flowers in Full Bloom

### ISSUE THREAD

**Issue by AthulKkumar** [godkingjay/LeetCode#79]
### Difficulty

Hard

### Problem Description

You are given a 0-indexed 2D integer array flowers, where flowers[i] = [starti, endi] means the ith flower will be in full bloom from starti to endi (inclusive). You are also given a 0-indexed integer array people of size n, where people[i] is the time that the ith person will arrive to see the flowers.

Return an integer array answer of size n, where answer[i] is the number of flowers that are in full bloom when the ith person arrives.

**Comment by AthulKkumar** [comment]
Can  I get assignend this

**Comment by aks057** [comment]
can you assign me?
