### ISSUE TITLE
[PROBLEM] 5. Longest Palindromic Substring

### ISSUE THREAD

**Issue by godkingjay** [godkingjay/LeetCode#91]
### Difficulty

Medium

### Problem Description

Given a string `s`, return *the longest palindromic substring* in `s`.

---

### Example 1:

**Input:** `s = "babad"`
**Output:** `"bab"`
**Explanation:**
```
"aba" is also a valid answer.
```

### Example 2:

**Input:** `s = "cbbd"`
**Output:** `"bb"`

---

### Constraints:
- `1 <= s.length <= 1000`
- `s` consist of only digits and English letters.

### Link

https://leetcode.com/problems/longest-palindromic-substring/

**Comment by VishnuAmit** [comment]
Hey @godkingjay . Kindly assign it to me. Id like to work on this issue

**Comment by VishnuAmit** [comment]
Hey @godkingjay . Done with the problem. Kindly check out my PR.
Thanks !
