### ISSUE TITLE
[PROBLEM] 7. Reverse Integer

### ISSUE THREAD

**Issue by godkingjay** [godkingjay/LeetCode#98]
### Difficulty

Medium

### Problem Description

<div class="xFUwe" data-track-load="description_content"><p>Given a signed 32-bit integer <code>x</code>, return <code>x</code><em> with its digits reversed</em>. If reversing <code>x</code> causes the value to go outside the signed 32-bit integer range <code>[-2<sup>31</sup>, 2<sup>31</sup> - 1]</code>, then return <code>0</code>.</p>

<p><strong>Assume the environment does not allow you to store 64-bit integers (signed or unsigned).</strong></p>

<p><strong class="example">Example 1:</strong></p>

<pre><strong>Input:</strong> x = 123
<strong>Output:</strong> 321
</pre>

<p><strong class="example">Example 2:</strong></p>

<pre><strong>Input:</strong> x = -123
<strong>Output:</strong> -321
</pre>

<p><strong class="example">Example 3:</strong></p>

<pre><strong>Input:</strong> x = 120
<strong>Output:</strong> 21
</pre>

<p><strong>Constraints:</strong></p>

<ul>
	<li><code>-2<sup>31</sup> &lt;= x &lt;= 2<sup>31</sup> - 1</code></li>
</ul>
</div>

### Link

https://leetcode.com/problems/reverse-integer/

**Comment by VSen910** [comment]
Hey I've got a Java solution, would you please assign this to me?

**Comment by VSen910** [comment]
I just noticed a C++ and Java solution for the same already exists in the repo whose space complexity is O(n), but I have a got a different approach to it whose time complexity is O(n) and space is O(1), so shall I go ahead with that?

**Comment by godkingjay** [comment]
> I just noticed a C++ and Java solution for the same already exists in the repo whose space complexity is O(n), but I have a got a different approach to it whose time complexity is O(n) and space is O(1), so shall I go ahead with that?

You can try doing it like this:

```java
// Solution https://github.com/godkingjay/LeetCode/issues/1
class Solution {
  /*
   * Code for Solution https://github.com/godkingjay/LeetCode/issues/1
   */
}


// Solution https://github.com/godkingjay/LeetCode/issues/2
class Solution {
  /*
   * Code for Solution https://github.com/godkingjay/LeetCode/issues/2
   */
}
```

or like this:

```
LeetCode/
├── [DIFFICULTY]/
│   ├── [PROBLEM]/
│   │   ├── README
│   │   ├── solution.java
│   │   ├── solution.cpp
│   │   ├── [MY APPROACH]/
│   │   │   ├── README
│   │   │   ├── solution.java
│   │   │   └── ...
│   │   └── ...
```
